import AuthProvider from "@/components/AuthProvider";
import NavbarRoot from "@/components/NavbarRoot";
import { Toaster } from "@/components/ui/sonner";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tunecraft",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${poppins.variable}
        ${inter.variable}
          antialiased bg-black`}
      >
        <AuthProvider>
          <Toaster />
          <NavbarRoot />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
